### ISSUE TITLE
Error: spawnSync git ENOENT

### ISSUE THREAD

**Issue by arklanq** [nexdrew/next-build-id#42]
The following error occurs in Docker container when building production image:

```text
#16 2.458 > Build error occurred
#16 2.461 <ref *1> Error: spawnSync git ENOENT
#16 2.461     at Object.spawnSync (internal/child_process.js:1067:20)
#16 2.461     at spawnSync (child_process.js:602:24)
#16 2.461     at Object.execFileSync (child_process.js:629:15)
#16 2.461     at gitSync (/build/node_modules/next-build-id/index.js:43:23)
#16 2.461     at AsyncFunction.nextBuildId.sync (/build/node_modules/next-build-id/index.js:170:8)
#16 2.461     at Object.<anonymous> (/build/next.config.js:9:32)
#16 2.461     at Module._compile (internal/modules/cjs/loader.js:1063:30)
#16 2.461     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
#16 2.461     at Module.load (internal/modules/cjs/loader.js:928:32)
#16 2.461     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
#16 2.461     at Module.require (internal/modules/cjs/loader.js:952:19)
#16 2.461     at require (internal/modules/cjs/helpers.js:88:18)
#16 2.461     at loadConfig (/build/node_modules/next/dist/next-server/server/config.js:8:94)
#16 2.461     at /build/node_modules/next/dist/build/index.js:2:227
#16 2.461     at /build/node_modules/next/dist/build/tracer.js:3:360
#16 2.461     at NoopTracer.withSpan (/build/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:47:16) {
#16 2.461   errno: -2,
#16 2.461   code: 'ENOENT',
#16 2.461   syscall: 'spawnSync git',
#16 2.461   path: 'git',
#16 2.461   spawnargs: [
#16 2.461     '--git-dir=/build/.git',
#16 2.461     '--work-tree=/build',
#16 2.461     'rev-parse',
#16 2.461     'HEAD'
#16 2.461   ],
#16 2.461   error: [Circular *1],
#16 2.461   status: null,
#16 2.461   signal: null,
#16 2.461   output: null,
#16 2.461   pid: 39,
#16 2.461   stdout: null,
#16 2.461   stderr: null
#16 2.461 }
#16 2.486 error Command failed with exit code 1.
#16 2.486 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by chulphan** [comment]
If you using jenkins + ELB then you could make .env.production.
