### ISSUE TITLE
Next.js build fails due to git  rev-parse HEAD error

### ISSUE THREAD

**Issue by darwin403** [nexdrew/next-build-id#54]
Using this in `next.config.js` is triggering the following error:

```
10:11:16.084 | > Build error occurred
-- | --
10:11:16.087 | Error: Command failed: git --git-dir=/vercel/path0/.git --work-tree=/vercel/path0 rev-parse HEAD
10:11:16.087 | fatal: not a git repository: '/vercel/path0/.git'
10:11:16.088 | at ChildProcess.exithandler (child_process.js:308:12)
10:11:16.088 | at ChildProcess.emit (events.js:315:20)
10:11:16.088 | at maybeClose (internal/child_process.js:1048:16)
10:11:16.088 | at Socket.&lt;anonymous&gt; (internal/child_process.js:439:11)
10:11:16.088 | at Socket.emit (events.js:315:20)
10:11:16.088 | at Pipe.&lt;anonymous&gt; (net.js:673:12) {
10:11:16.088 | killed: false,
10:11:16.088 | code: 128,
10:11:16.088 | signal: null,
10:11:16.089 | cmd: 'git --git-dir=/vercel/path0/.git --work-tree=/vercel/path0 rev-parse HEAD',
10:11:16.089 | stdout: '',
10:11:16.089 | stderr: "fatal: not a git repository: '/vercel/path0/.git'\n"
10:11:16.089 | }
10:11:16.103 | error Command failed with exit code 1.
10:11:16.103 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
10:11:16.123 | Error: Command "yarn run build" exited with 1
```

I suppose this is arising due to the SHA that is to be generated for the build-id by this module using the command `git --git-dir=/vercel/path0/.git --work-tree=/vercel/path0 rev-parse HEAD` which is triggering the build failure.

**Solution:** Remove this module from your next.config.js and vercel will build your next.js application just fine!

**Comment by darwin403** [comment]
Just noticed that the issue has already been discussed at: #29

**Comment by darwin403** [comment]
Just noticed that the issue has already been discussed at: #29
